### ISSUE TITLE
How to visualize the output object pose?

### ISSUE THREAD

**Issue by buaacyw** [NVlabs/dex-ycb-toolkit#2]
Thanks for your great work!
But it seems that the given code can't visualize the output object pose?

**Comment by ychao-nvidia** [comment]
To visualize predicted object pose, you can modify the example for visualizing ground-truth pose:
https://github.com/NVlabs/dex-ycb-toolkit/blob/master/examples/visualize_pose.py

and get something like the visualization here:
https://github.com/NVlabs/dex-ycb-toolkit#loading-dataset-and-visualizing-samples.

**Comment by buaacyw** [comment]
Thanks for your quick reply!
