### ISSUE TITLE
hand pose, translatation and rotation parameters

### ISSUE THREAD

**Issue by YorkWang-Go** [NVlabs/dex-ycb-toolkit#22]
Thanks for your great work! I have some problems when I try to ues your dataset, and hope to get your help!

1.  I find that in the `/annotations/DEX_YCB_s0_train_data.json`, there is also `mano_param` for every image. I wonder whether they are in camera frame or world frame. If I want to use the hand parameters in this json file, how can I get the parameters of the hand translation(1X3) and the object rotation and translation(4X4)?
2. I tried to visualize the hand pose using the paramaters both in the label file and the json file, but I found neither of them was right and  they were different from each other. I couldn't figure out the reason. In my opinion, even if the paramaters of the object translatation I used were wrong, the hand pose at least should be right. So the result really confused me.

Thanks again and looking forward to your reply!

**Comment by ychao-nvidia** [comment]
This is out of context of this repo. `DEX_YCB_s0_train_data.json` seems to be created by the authors of the [HandOccNet](https://github.com/namepllet/HandOccNet) repo. You may want to seek answers there.

**Comment by YorkWang-Go** [comment]
Oh, I'm sorry that I made a mistake. Thanks!
