### ISSUE TITLE
Inconsistency in pose_y for per_image and per_sequence

### ISSUE THREAD

**Issue by WeedsInML** [NVlabs/dex-ycb-toolkit#26]
Hi, when I compare the pose_y of 'label*.npz' in folder 840412060917 and 'pose.npz', I find the pose_y of num_obj=0 is different. As you said in https://github.com/NVlabs/dex-ycb-toolkit/issues/12#issuecomment-932351769,  object 6D pose should be the same in two formats.

Is there something that I made a mistake with?

I really appreciate any help you can provide.

**Comment by ychao-nvidia** [comment]
Yes they should be the same. The only difference is that `labels_*.npz` stores pose in `[rotation matrix | translation]` (i.e. array of shape `[num_obj, 3, 4]`), and `pose.npz` stores pose in quaternion (x, y, z, w) + translation (x, y, z) (i.e. array of shape `[num_obj, 7]`).

You can verify by:
```
import numpy as np
data_1 = np.load("pose.npz")
data_2 = np.load("840412060917/labels_000000.npz")
data_1["pose_y"][0, :, 4:7] - data_2["pose_y"][:, :, 3]
```
This should print:
```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)
```

**Comment by WeedsInML** [comment]
I test this on subject '20200709_141754', and print all sequence results:
[[6.0200691e-06 5.9148297e-05 1.0383129e-04]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]]
[[0.01726721 0.08576483 0.05797118]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[ 0.0016662   0.0015748  -0.00072074]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 5.5402517e-05  8.5055828e-05 -3.8921833e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[ 0.00058112  0.00046296 -0.0002352 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.00084591  0.00093009 -0.00035799]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.01887107 0.17651895 0.15353948]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.00811425 0.01419407 0.00232977]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01931158 0.19092534 0.16893989]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.00635861 0.01007815 0.00069791]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01030833 0.02843745 0.01115328]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01811427 0.17071517 0.1480633 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[ 8.9436769e-05  2.0024367e-04 -1.3893843e-04]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[ 0.00053218  0.00065827 -0.00016922]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00025918 -0.00033276  0.00017625]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.0168142  0.1895605  0.17061663]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01766749 0.19460633 0.17584169]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01808855 0.1879777  0.16708446]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-3.5369396e-04 -1.4234334e-04  8.8512897e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[ 3.0696392e-04  4.0209852e-04 -7.4625015e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[0.0189376  0.19260678 0.17163622]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01830031 0.11419665 0.08768904]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.00084168 -0.00087095  0.00011998]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.01741403 0.10450195 0.07738519]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01828891 0.18423161 0.1633864 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-2.6205182e-04 -5.5509247e-04  3.5643578e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]
[[0.01908842 0.19378316 0.17351103]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.00080958 -0.00079309  0.00045246]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.01560996 0.07486957 0.04956919]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.00093533 -0.00099242  0.00014204]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.01200888 0.04469103 0.0244742 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01711486 0.16289523 0.14120716]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01518577 0.19055934 0.17439437]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.01353121 0.09176448 0.07020825]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.00047877 -0.0013401  -0.00022781]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.0038323  -0.00410088  0.0010131 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.0025363  -0.00625501 -0.00215918]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00811425 -0.01419407 -0.00232977]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00852965 -0.02079241 -0.00688362]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00996509 -0.028158   -0.01140976]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.00473517 0.15528336 0.15640134]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.01348539 -0.0461273  -0.02402776]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00190681 -0.01789995 -0.01457977]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[0.00299339 0.13003603 0.13534385]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[0.00259565 0.10572772 0.109586  ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-0.01620606 -0.08466903 -0.05833274]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.0119375  -0.08910502 -0.06999564]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00085494  0.08610308  0.09499365]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00335217 -0.04966028 -0.04741997]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00437601 -0.06808568 -0.06509846]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01871985 -0.13265453 -0.10723412]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00224549  0.0519524   0.05825394]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01884976 -0.14948949 -0.12502003]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01882669 -0.15776396 -0.13277262]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.00036417 -0.04028502 -0.04317391]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00899233 -0.14931363 -0.14135182]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01824886 -0.17580123 -0.15376115]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00025313  0.01382753  0.0159843 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01830709 -0.18447557 -0.16332465]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00094508  0.00631741  0.00843054]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01904249 -0.19089778 -0.16911167]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01956794 -0.19323333 -0.17148489]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.00067581 -0.06153185 -0.06614912]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01667601 -0.19345792 -0.17567396]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01852794 -0.19510596 -0.17530733]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01721208 -0.19411506 -0.17584479]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.00191881 -0.05256061 -0.05870706]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.00140664 -0.03636089 -0.0420655 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01612107 -0.19204648 -0.17448205]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01721473 -0.19212459 -0.17364389]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.01729015 -0.19122522 -0.17196912]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.00226066 -0.03998104 -0.04554629]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]

**Comment by WeedsInML** [comment]
The difference exists in the grasped object, the rest objects are the same.

**Comment by ychao-nvidia** [comment]
Not sure how you got the printout above. Can you provide a code snippet for reproduction?

**Comment by WeedsInML** [comment]
seq_poses_file = '/media/xywang/Samsung_T5/datasets/dexycb/20200709-subject-01/20200709_141754/pose.npz'
  label_paths_dir = '/media/xywang/Samsung_T5/datasets/dexycb/20200709-subject-01/20200709_141754/840412060917'
  
  labels_data_pose_m = []
  labels_data_pose_y = []
  labels_data_seg = []
  labels_data_joint3d = []
  labels_data_joint2d = []

  label_paths_template = os.path.join(label_paths_dir, '*.npz')
  label_paths = glob(label_paths_template)
  for i in range(len(label_paths)):
    label_path = label_paths[i]

    label = np.load(label_path)
    seg = label['seg']
    pose_y = label['pose_y']
    pose_m = label['pose_m']
    joint_3d = label['joint_3d']
    joint_2d = label['joint_2d']
   
    labels_data_seg.append(seg)
    labels_data_pose_y.append(pose_y)
    labels_data_pose_m.append(pose_m)
    labels_data_joint3d.append(joint_3d)
    labels_data_joint2d.append(joint_2d)
  labels_data_seg = np.array(labels_data_seg) # (72, 480, 640)
  labels_data_pose_y = np.array(labels_data_pose_y) # (72, 4, 3, 4)
  labels_data_pose_m = np.array(labels_data_pose_m) # (72, 1, 51)
  labels_data_joint3d = np.array(labels_data_joint3d) # (72, 1, 21, 3)
  labels_data_joint2d = np.array(labels_data_joint2d) # (72, 1, 21, 2)


  data = np.load(seq_poses_file)
  seq_pose_m = data['pose_m'] # (72, 1, 51)
  seq_pose_y = data['pose_y'] # (72, 4/5, 7)

  data_1 = seq_pose_y # (72, 5, 7)
  data_2 = labels_data_pose_y # (72, 5, 3, 4)

  for i in range(data_2.shape[0]):
    diff = data_1[i,:,4:7] - data_2[i,:,:,3]
    print(np.array(diff))

**Comment by ychao-nvidia** [comment]
This is a bug of your code. Try printing out `label_paths`. You need this line after calling `glob()`: `label_paths = sorted(label_paths)`.

**Comment by WeedsInML** [comment]
Yes! Thank you so much! I'll close this.
