### ISSUE TITLE
MANO pose coefficients (theta)

### ISSUE THREAD

**Issue by wetoo-cando** [NVlabs/dex-ycb-toolkit#32]
Hello @ychao-nvidia,

From the README:
```
pose_m: A float32 numpy array of shape [1, 51] holding the pose of the hand. pose_m[:, 0:48] 
stores the MANO pose coefficients in PCA representation, and pose_m[0, 48:51] stores the 
translation. If the image does not have a visible hand or the annotation does not exist, 
pose_m will be all 0.
``` 
Where can I find the code for the above pose estimation?

Thanks!

**Comment by ychao-nvidia** [comment]
This is part of the data annotation and unfortunately the code of that process is not released.

**Comment by wetoo-cando** [comment]
Ok thanks.

**Comment by wetoo-cando** [comment]
@ychao-nvidia 

Can you please check if my notes below are correct? Especially the places marked with '???'

Thank you!

```

# Notes based on https://github.com/NVlabs/dex-ycb-toolkit/issues/23
In the labels.npz files:
Hand pose are all represented in MANO format.

pose_m[:, 0:3] stores the global rotation (seems like this is the wrist joint???) 
in camera (???) coordinate system.

pose_m[:, 3:48] stores the finger articulated pose in local frame 
(local means local to the hand??? Where on the hand is this exactly located???)

pose_m[:, 48:51] store the global translation <-- "is applied to a ad-hoc root joint that 
does not belong to any of the hand joints. The representation does not allow any rotation 
of this root joint." The translation is in camera (???) coordinate system.
```

**Comment by ychao-nvidia** [comment]
> pose_m[:, 0:3] stores the global rotation (seems like this is the wrist joint???) in camera (???) coordinate system.

Yes, it is the wrist joint. The term "global" can be misleading here depending on what you mean by global, since in MANO the wrist is not the root joint. Yes, it is in the camera coordinate system.

> pose_m[:, 3:48] stores the finger articulated pose in local frame (local means local to the hand??? Where on the hand is this exactly located???)

Yes, local to the hand. These are the joint angles in the kinematic tree. You can visualize the joint locations by running the demo in the [manopth](https://github.com/hassony2/manopth) repo.

> pose_m[:, 48:51] store the global translation <-- "is applied to a ad-hoc root joint that  does not belong to any of the hand joints. The representation does not allow any rotation of this root joint." The translation is in camera (???) coordinate system.

Yes, translation is in camera coordinates.

**Comment by wetoo-cando** [comment]
Thanks for the helpful response @ychao-nvidia

**Comment by bb0928** [comment]
hi i am wondering if pose_m[:, 0:3],pose_m[:, 3:48] is represented by axis-angle? thanks.

**Comment by bb0928** [comment]
@ychao-nvidia hi i am wondering if pose_m[:, 0:3],pose_m[:, 3:48] is represented by axis-angle? thanks.

**Comment by ychao-nvidia** [comment]
- `pose_m[:, 0:3]` is in axis-angle. 
- `pose_m[:, 3:48]` is in PCA representation, which will first be converted to axis-angle when computing joints and vertices in [manopth](https://github.com/hassony2/manopth).

**Comment by bb0928** [comment]
Thanks a lot
