### ISSUE TITLE
pyglet 2.0.9 requires Python 3.8 or newer.

### ISSUE THREAD

**Issue by chorhc** [NVlabs/dex-ycb-toolkit#37]
Hi, thank you for the work.
I am facing some problem while running the python examples/visualize_pose.py code. I built my virtual environment with Python 3.7 as the code was tested with Python 3.7, and everything I have cloned from the github is built into this same virtual environment. However, I am getting the error "pyglet 2.0.9 requires 3.8 or newer.". What should I do?

**Comment by ychao-nvidia** [comment]
You can try downgrading `pyglet`:

```
pip install pyglet==1.5.27
```

**Comment by chorhc** [comment]
Hi, thank you so much for the fast reply. It is working perfectly now!
