### ISSUE TITLE
Banana point cloud looks flattened 

### ISSUE THREAD

**Issue by chorhc** [NVlabs/dex-ycb-toolkit#39]
Hi, thank you for your work. I have extracted the 3D poses for the banana, loaded it into trimesh and converted it into point cloud, then visualize using matplotlib. However, I realized that the banana point cloud looks "flatten", I have tried the same approach with other objects, such as power drill, master chef can, boxes, and they all look correct. Is there any problem with the 3D poses for banana object? I loaded it specifically from /20200709-subject-01/20200709_145401/836212060125/labels_000070.npz
I realized that /20200709-subject-01/20200709_145401/839512060362/labels_000067.npz has the same flattened problem as well.
However, /20200709-subject-01/20200709_145401/840412060917/labels_000064.npz looks correct (not flattened)
![Screenshot from 2024-01-11 00-21-19](https://github.com/NVlabs/dex-ycb-toolkit/assets/85432645/676388d7-6354-44bd-83b1-3ecadb3e53fb)

**Comment by ychao-nvidia** [comment]
The issue is unclear to me. Do you have a visualization of the "flattened" point cloud?

**Comment by chorhc** [comment]
Hi sorry, I realised that I have understood the dimension of the poses wrongly, hence I retrieved the wrong pose, which caused my resulting mesh looking weird!
