### ISSUE TITLE
Question about dataset S2 (#seq)

### ISSUE THREAD

**Issue by trevor-taeyeop** [NVlabs/dex-ycb-toolkit#4]
https://github.com/NVlabs/dex-ycb-toolkit/blob/e957432e0f81a477a897698340bbb69c05a3d9d6/dex_ycb_toolkit/dex_ycb.py#L157

In Tab 9 (main paper), the number of sequences (#seq) would be all 1,000 for train, Val, test instead of 750/125/125. As I understood, the number of sequences(#seq) is independent of the number of camera view points(#view). Have I missed something? 
`Simple equation for #seq(1,000) = #subject_ind(10) * #sequnce_ind(100)`

**Comment by ychao-nvidia** [comment]
You're right. This is an error. The number of sequences (#seq) for train/val/test should be 1,000/1,000/1,000 for S2 (unseen views) in the [arXiv paper Tab. 9](https://arxiv.org/pdf/2104.04631.pdf).

**Comment by trevor-taeyeop** [comment]
Thanks for your reply!
