### ISSUE TITLE
Why y-axis and z-axis multiply by -1?

### ISSUE THREAD

**Issue by chorhc** [NVlabs/dex-ycb-toolkit#40]
Hi thank you for the work, just wondering why in file like examples/visualize_pose.py:
Why do we need to multiply those axes by -1? Is it alright if we don't?

In line 58-59: 
    pose[1] *= -1
    pose[2] *= -1

In line 78-79:
    vert[:, 1] *= -1
    vert[:, 2] *= -1

**Comment by ychao-nvidia** [comment]
This is for converting from OpenCV to OpenGL convention. Poses in the annotation are saved in OpenCV camera coordinates, while rendering with `pyrender` requires OpenGL.

**Comment by chorhc** [comment]
Oh, I understand now. Thank you for the quick reply!
